language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thiagoslima/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thiagoslima/react-test npm test

after_success:
  - docker build -t thiagoslima/multi-api ./api
  - docker build -t thiagoslima/multi-client ./client
  - docker build -t thiagoslima/multi-nginx ./nginx
  - docker build -t thiagoslima/multi-worker ./worker
  # Login in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push to the docker hub
  - docker push thiagoslima/multi-api
  - docker push thiagoslima/multi-client
  - docker push thiagoslima/multi-nginx
  - docker push thiagoslima/multi-worker
